[package]
name = "upspot"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-multipart = "0.6"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
sanitize-filename = "0.6.0"
qrcode = "0.14.1"
